project_doc_fallback_filenames = [ "CLAUDE.md" ]
suppress_unstable_features_warning = true
sandbox_mode = "workspace-write"
approval_policy = "on-request"
model = "gpt-5.5"
review_model = "gpt-5.5"
model_reasoning_effort = "xhigh"
model_context_window = 1000000
model_auto_compact_token_limit = 500000
plan_mode_reasoning_effort = "high"

[features]
shell_tool = true
apply_patch_freeform = true
shell_snapshot = true
undo = true
unified_exec = true
multi_agent = true
steer = true
prevent_idle_sleep = true
child_agents_md = true
memories = true
sqlite = true
fast_mode = true

[memories]
consolidation_model = "gpt-5.4"
extract_model = "gpt-5.4"
max_raw_memories_for_consolidation = 512
max_unused_days = 30
max_rollout_age_days = 45

[projects."/Users/loopq/dev/git/zthd/avatar/Avatar-Android"]
trust_level = "trusted"

[projects."/Users/loopq/dev/tools/ccwake"]
trust_level = "trusted"

[projects."/Users/loopq/dev/tools/xiaomitest"]
trust_level = "trusted"

[projects."/Users/loopq/dev/tools/storyline"]
trust_level = "trusted"

[projects."/Users/loopq/dev/zthd/story"]
trust_level = "trusted"

[projects."/Users/loopq/dev/tools/zerogravity"]
trust_level = "trusted"

[projects."/Users/loopq/dev/tools/aiconsole"]
trust_level = "trusted"

[projects."/Users/loopq/dev/git/loopq/trend.github.io"]
trust_level = "trusted"

[projects."/"]
trust_level = "trusted"

[projects."/private/tmp"]
trust_level = "trusted"

[projects."/Users/loopq/dev/git/loopq/tinydownload"]
trust_level = "trusted"

[projects."/Users/loopq/dev/git/zthd/UIKit"]
trust_level = "trusted"

[projects."/Users/loopq/Downloads"]
trust_level = "trusted"

[notice]
fast_default_opt_out = true

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[tui]
status_line = ["project-name", "model-with-reasoning", "context-used", "five-hour-limit", "weekly-limit", "task-progress"]

[tui.model_availability_nux]
"gpt-5.5" = 4
